### ISSUE TITLE
Script will deactivate active window and shows dock movements

### ISSUE THREAD

**Issue by martinvandiemen** [pbowden-msft/msupdatehelper#4]
I really like this script and have been testing it for some time. I noticed that when it's running (using Jamf) the active window is deselected also you can see a small movement in the Dock when this occurs. When all apps are being updated the deselection of the active window is a but annoying.

**Comment by khourybrazil** [comment]
It's actually not deselected, what's happening is it's stealing focus and it is really annoying. There's no actual window so the menu bar doesn't update but if you use the python script found [here](https://apple.stackexchange.com/a/170699) you can see Microsoft Update Assistant is in fact stealing the focus away from the active application.

**Comment by pbowden-msft** [comment]
Yes, it's a bug in core MAU, rather than the script.

**Comment by khourybrazil** [comment]
Thanks @pbowden-msft Any chance that bug is being tracked somewhere publicly or should we just keep an eye on the change logs?

**Comment by kylejericson** [comment]
@pbowden-msft When will this be fixed?

**Comment by kylejericson** [comment]
@pbowden-msft Can we get an update on this issue?

**Comment by pbowden-msft** [comment]
@kylejericson @martinvandiemen @khourybrazil the focus stealing issue was finally fixed in MAU 4.15 which released earlier this week. You can download the build from https://go.microsoft.com/fwlink/?linkid=830196
You'll still see slight movement in the dock when the script runs, but the foreground app will no longer lose focus. Thanks for your patience!
